name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        install-dir: 'C:\Users\runneradmin\dotnet'

    - name: Setup .NET Framework 4.6.2
      run: |
        Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=2099466' -OutFile .\dotnet-framework-462-offline-installer.exe
        $process = Start-Process -FilePath .\dotnet-framework-462-offline-installer.exe -ArgumentList '/q /norestart' -PassThru
        $process.WaitForExit()
      shell: pwsh
