name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.6.2'
        
    - name: Install .NET Framework 4.6.2 Developer Pack
      run: |
        choco install netfx-4.6.2-devpack

    - name: Restore dependencies
      run: nuget restore

    - name: Build solution
      run: msbuild -p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe **\*Tests.dll
